### PR TITLE
feat: publish to JSR

### PR DESCRIPTION
**Pull request by eliassjogreen**

### CODE REVIEW

**Comment by MierenManz** [comment]
I see a lot of added explicit types, is that a requirement for jsr?

**Comment by MierenManz** [comment]
Also wouldn't this mean that our tests in theory also need to be done on bun (and maybe node) ?

**Review by MierenManz — APPROVED** [review]
Lgtm!

**Comment by eliassjogreen** [comment]
> I see a lot of added explicit types, is that a requirement for jsr?

Yep indeed. Both your comments are true :)

**Pull request merged**
