### PR TITLE
feat: Add tests for all types

### PR DESCRIPTION
**Pull request by MierenManz**

### CODE REVIEW

**Comment by MierenManz** [comment]
This will fail on 2 tests. One of which is adressed by #15 andf the other one I don't know what is happening

Still needs struct tests but I have asked if elias can do these because I don't fully understand them

**Comment by MierenManz** [comment]
last test that is failing is due to some type error that is ignored. @eliassjogreen could you look at that? because I have no idea what the code is trying to achieve

**Comment by eliassjogreen** [comment]
Fixed the typed array issue, just rebase and it should work :D

**Comment by MierenManz** [comment]
@eliassjogreen PTAL

**Review by eliassjogreen — APPROVED** [review]

**Pull request merged**
